import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { PublicProfileShell } from "./PublicProfileShell";
import type { PublicProfile } from "@/types/signal";
import { asFiniteNumber } from "@/lib/utils";

interface Props {
  params: Promise<{ username: string }>;
}

const API_BASE = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000/v1";

async function fetchPublicProfile(username: string): Promise<PublicProfile | null> {
  try {
    const res = await fetch(`${API_BASE}/profiles/${username}`, {
      next: { revalidate: 60 },
    });
    if (res.status === 404) return null;
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    return res.json() as Promise<PublicProfile>;
  } catch {
    return null;
  }
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { username } = await params;
  const data = await fetchPublicProfile(username);
  const displayName = data?.full_name ?? `@${username}`;
  const score = data?.profile
    ? ((
        (asFiniteNumber(data.profile.technical_execution) ?? 0) +
        (asFiniteNumber(data.profile.problem_complexity) ?? 0) +
        (asFiniteNumber(data.profile.communication_quality) ?? 0)
      ) / 3).toFixed(1)
    : null;

  return {
    title: `${displayName} — SIGNAL Capability Profile`,
    description: score
      ? `SIGNAL score ${score}/9.0 · ${data?.verified_capability_count ?? 0} verified capabilities`
      : `Evidence-based capability profile for @${username}, generated by SIGNAL EDU.`,
    openGraph: {
      title: `${displayName} on SIGNAL`,
      description: "Technical Execution · Problem Complexity · Communication Quality",
      type: "profile",
    },
  };
}

export default async function PublicProfilePage({ params }: Props) {
  const { username } = await params;
  if (!username) notFound();

  const data = await fetchPublicProfile(username);

  return <PublicProfileShell username={username} data={data} />;
}
